volumes:
  homebox-data:
    external: true
    name: ${INVENTORY_DATA_VOLUME:-homebox-data}

networks:
  proxy:
    external: true
    name: ${PROXY_NETWORK_NAME:-proxy}

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    volumes:
      - homebox-data:/data
    environment:
      - INVENTORY_HOSTNAME=${INVENTORY_HOSTNAME}
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.checkrr.rule=Host(`inventory.nas.local`)
      - traefik.http.routers.checkrr.entrypoints=web
